@echo off
REM ============================================================
REM  配置钉钉告警通道（运维系统 Step 10 / OPS-FR-12）
REM  作用：粘贴钉钉机器人地址 -^> 生成配置 -^> 重启服务 -^> 发测试消息
REM  红线：本文件必须 GBK 编码 + CRLF 行尾 + 无 BOM，禁止 chcp 65001；
REM        生成的 yml 与发给钉钉的 JSON 一律 ASCII（GBK 字节会乱码/报错）
REM ============================================================
setlocal

REM 需要管理员权限（要重启 Windows 服务），不足则自动提权重跑
net session >nul 2>&1
if errorlevel 1 (
    echo 需要管理员权限，正在弹出授权窗口...
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b 0
)

set OPS=D:\IT\ops
set AM_YML=%OPS%\alertmanager\alertmanager.yml
set DT_CFG=%OPS%\dingtalk-webhook\config.yml

echo ============================================================
echo            配置钉钉告警通道
echo ============================================================
echo.
echo  使用前请先在钉钉群里添加机器人拿到 Webhook 地址：
echo    钉钉群 -^> 群设置 -^> 机器人 -^> 添加机器人 -^> 自定义
echo    安全设置建议选「加签」（会多给一个 SEC 开头的密钥）
echo.

set /p WEBHOOK=请粘贴 Webhook 地址后回车：
if "%WEBHOOK%"=="" (
    echo 没有输入地址，已取消，未做任何修改。
    pause
    exit /b 1
)
echo %WEBHOOK% | findstr /C:"oapi.dingtalk.com/robot/send" >nul
if errorlevel 1 (
    echo 地址不像钉钉机器人地址（应包含 oapi.dingtalk.com/robot/send），已取消。
    pause
    exit /b 1
)

set /p SECRET=请输入加签密钥（SEC 开头；没选加签就直接回车）：

echo.
echo 正在写入配置...

REM ---- 钉钉适配器配置（只写 ASCII，中文注释会让解析器报错）----
> "%DT_CFG%" echo # auto-generated by configure-dingtalk.bat - ASCII only
>> "%DT_CFG%" echo targets:
>> "%DT_CFG%" echo   ops:
>> "%DT_CFG%" echo     url: %WEBHOOK%
if not "%SECRET%"=="" (
    >> "%DT_CFG%" echo     secret: %SECRET%
)

REM ---- Alertmanager 主配置（只写 ASCII）----
> "%AM_YML%" echo # auto-generated by configure-dingtalk.bat
>> "%AM_YML%" echo global:
>> "%AM_YML%" echo   resolve_timeout: 5m
>> "%AM_YML%" echo route:
>> "%AM_YML%" echo   receiver: dingtalk
>> "%AM_YML%" echo   group_by: [alertname, severity]
>> "%AM_YML%" echo   group_wait: 30s
>> "%AM_YML%" echo   group_interval: 5m
>> "%AM_YML%" echo   repeat_interval: 4h
>> "%AM_YML%" echo receivers:
>> "%AM_YML%" echo   - name: dingtalk
>> "%AM_YML%" echo     webhook_configs:
>> "%AM_YML%" echo       - url: http://127.0.0.1:8060/dingtalk/ops/send
>> "%AM_YML%" echo         send_resolved: true

echo 正在重启告警服务...
net stop agent-dingtalk-webhook >nul 2>&1
net start agent-dingtalk-webhook
if errorlevel 1 (
    echo [失败] 钉钉适配器服务启动失败，请打开 services.msc 查看 agent-dingtalk-webhook
    pause
    exit /b 1
)
net stop agent-alertmanager >nul 2>&1
net start agent-alertmanager
if errorlevel 1 (
    echo [失败] Alertmanager 服务启动失败，请打开 services.msc 查看 agent-alertmanager
    pause
    exit /b 1
)

echo 正在发送测试消息到钉钉群...
curl -s -X POST "http://127.0.0.1:8060/dingtalk/ops/send" -H "Content-Type: application/json" -d "{\"version\":\"4\",\"status\":\"firing\",\"alerts\":[{\"status\":\"firing\",\"labels\":{\"alertname\":\"DingTalkTest\",\"severity\":\"info\"},\"annotations\":{\"summary\":\"DingTalk alert test\",\"description\":\"Alert channel is ready if you see this message.\"},\"startsAt\":\"2026-01-01T00:00:00.000Z\"}]}" >nul

echo.
echo ============================================================
echo  配置完成！请到钉钉群确认是否收到测试消息。
echo  没收到：检查 Webhook/加签是否抄错，再看日志
echo  %OPS%\dingtalk-webhook\logs\
echo ============================================================
pause
exit /b 0
