-- agent-platform/backend/src/test/resources/schema-h2.sql
-- H2兼容模式下的建表脚本（用于测试环境）

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100) NOT NULL,
    email       VARCHAR(100),
    avatar      VARCHAR(500),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    description VARCHAR(200),
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    code        VARCHAR(100) NOT NULL,
    resource    VARCHAR(50)  NOT NULL,
    action      VARCHAR(50)  NOT NULL,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id     BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS agent_groups (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    icon        VARCHAR(50),
    description VARCHAR(500),
    sort_order  INT          NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS agents (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    avatar      VARCHAR(500),
    group_id    BIGINT       NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    config      TEXT,
    parent_id   BIGINT,
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS skills (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    type        VARCHAR(30)  NOT NULL DEFAULT 'SEQUENCE',
    config      TEXT,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS skill_steps (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id    BIGINT       NOT NULL,
    step_order  INT          NOT NULL,
    name        VARCHAR(100) NOT NULL,
    action      VARCHAR(100) NOT NULL,
    config      TEXT,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS workflows (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    owner_id    BIGINT       NOT NULL,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT          NOT NULL DEFAULT 0,
    version     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS workflow_nodes (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id   BIGINT       NOT NULL,
    node_id       VARCHAR(50)  NOT NULL,
    type          VARCHAR(30)  NOT NULL,
    position_x    DOUBLE       NOT NULL DEFAULT 0,
    position_y    DOUBLE       NOT NULL DEFAULT 0,
    label         VARCHAR(100),
    config        TEXT,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       INT          NOT NULL DEFAULT 0,
    version       INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS workflow_edges (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     BIGINT       NOT NULL,
    source_node_id  VARCHAR(50)  NOT NULL,
    target_node_id  VARCHAR(50)  NOT NULL,
    source_handle   VARCHAR(50),
    target_handle   VARCHAR(50),
    label           VARCHAR(100),
    condition       TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT          NOT NULL DEFAULT 0,
    version         INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS execution_logs (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     BIGINT       NOT NULL,
    workflow_name   VARCHAR(100),
    parent_execution_id BIGINT,
    root_execution_id BIGINT,
    source_type VARCHAR(30),
    source_id BIGINT,
    node_id VARCHAR(100),
    external_thread_id VARCHAR(200),
    checkpoint_ref VARCHAR(500),
    trace_id VARCHAR(100),
    triggered_by    BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    variables       TEXT,
    node_logs       TEXT,
    started_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    duration        BIGINT,
    error_message   TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT          NOT NULL DEFAULT 0,
    version         INT          NOT NULL DEFAULT 0
);

-- 测试初始数据（MERGE避免重复插入）
MERGE INTO roles (id, name, code, description) KEY(id) VALUES (1, '普通用户', 'user', '可以创建和执行工作流');
MERGE INTO roles (id, name, code, description) KEY(id) VALUES (2, 'Agent管理员', 'agent_admin', '可以管理Agent和技能');
MERGE INTO roles (id, name, code, description) KEY(id) VALUES (3, '系统管理员', 'admin', '拥有所有权限');

MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (1, '查看Agent', 'agent:read', 'agent', 'read');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (2, '创建Agent', 'agent:create', 'agent', 'create');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (3, '编辑Agent', 'agent:update', 'agent', 'update');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (4, '删除Agent', 'agent:delete', 'agent', 'delete');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (5, '发布Agent', 'agent:publish', 'agent', 'publish');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (6, '管理技能', 'skill:manage', 'skill', 'manage');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (7, '查看工作流', 'workflow:read', 'workflow', 'read');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (8, '创建工作流', 'workflow:create', 'workflow', 'create');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (9, '编辑工作流', 'workflow:update', 'workflow', 'update');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (10, '删除工作流', 'workflow:delete', 'workflow', 'delete');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (11, '发布工作流', 'workflow:publish', 'workflow', 'publish');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (12, '执行工作流', 'execution:run', 'execution', 'run');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (13, '查看执行日志', 'execution:read', 'execution', 'read');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (14, '管理用户', 'user:manage', 'user', 'manage');
MERGE INTO permissions (id, name, code, resource, action) KEY(id) VALUES (15, '管理角色', 'role:manage', 'role', 'manage');

-- admin拥有所有权限
DELETE FROM role_permissions WHERE role_id = 3;
INSERT INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions;

-- 测试admin用户（密码: admin123），ID=100避免与测试插入数据冲突
MERGE INTO users (id, username, password, email, status) KEY(id)
VALUES (100, 'admin', '$2b$10$dinNKZ7q5nyOQXsC.P6uo.eqMpM6WlTeRO.2yV26dGK4V1tV0p2Kq', 'admin@platform.com', 'ACTIVE');

MERGE INTO user_roles (user_id, role_id) KEY(user_id, role_id) VALUES (100, 3);

-- chat_sessions (H2 compatible)
CREATE TABLE IF NOT EXISTS chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200),
    agent_id BIGINT,
    workflow_id BIGINT,
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    variables TEXT,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    version INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    metadata TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- execution_step_logs (H2 compatible)
CREATE TABLE IF NOT EXISTS execution_step_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    node_id VARCHAR(50),
    skill_id BIGINT,
    step_order INTEGER,
    step_name VARCHAR(200),
    action VARCHAR(30),
    input_data TEXT,
    output_data TEXT,
    status VARCHAR(20),
    duration BIGINT,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- user_memories (H2 compatible)
CREATE TABLE IF NOT EXISTS user_memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50),
    memory_key VARCHAR(200),
    memory_value TEXT,
    source VARCHAR(50),
    confidence DECIMAL(3,2) DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- llm_providers (H2 compatible)
CREATE TABLE IF NOT EXISTS llm_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    display_name VARCHAR(100),
    protocol VARCHAR(30),
    api_endpoint VARCHAR(500),
    api_key_enc TEXT,
    models TEXT,
    config TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    sort_order INTEGER DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    version INTEGER DEFAULT 0
);

-- user_llm_providers (H2 compatible)
CREATE TABLE IF NOT EXISTS user_llm_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_name VARCHAR(50) NOT NULL,
    api_endpoint VARCHAR(500),
    api_key_enc TEXT,
    models TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    version INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS agent_permissions (
    id              BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id        BIGINT    NOT NULL,
    user_id         BIGINT    NOT NULL,
    can_use         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_read_prompt BOOLEAN   NOT NULL DEFAULT FALSE,
    can_copy        BOOLEAN   NOT NULL DEFAULT FALSE,
    granted_by      BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT       NOT NULL DEFAULT 0,
    version         INT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_agent_permissions_agent_user UNIQUE (agent_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_permissions_user ON agent_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_permissions_agent ON agent_permissions(agent_id);

-- system_settings (H2 compatible)
CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO system_settings (id, setting_key, setting_value, description) KEY(id)
VALUES (1, 'auth.access_token_expiration_ms', '900000', 'Access token expiration in milliseconds');
