spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${FILE_KEEPER_DB_URL:jdbc:postgresql://localhost:5432/file_keeper}
    username: ${FILE_KEEPER_DB_USERNAME:postgres}
    password: ${FILE_KEEPER_DB_PASSWORD:postgres}
